spring.application.name=finance-tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/finance_tracker
spring.datasource.username=postgres
spring.datasource.password=Rakeshk@326

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret = 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration = 86400000